Repository athayogaio/pwa, pull requests merged in 2023-02, with the labels that each got.

#203 Update pipeline
  .env/.ci-env.develop
  .env/.ci-env.develop.test
  .env/.ci-env.master
  .env/.ci-env.master.test
  .env/.ci-env.stage
  .env/.ci-env.stage.test
  Jenkinsfile
  docker-compose.yml
Labels: DevOps, Feature

#224 Add volume for elasticsearch
  docker-compose.yml
Labels: DevOps, Feature

#240 Add publish report after test failure
  Jenkinsfile
Labels: DevOps, Feature

#243 Fix pipeline
  Jenkinsfile
Labels: DevOps, Bugfix

#244 Fix docker-compose.yml
  Jenkinsfile
  docker-compose.yml
Labels: DevOps, Bugfix

#246 Pipeline fixes
  Jenkinsfile
  docker-compose.yml
  frontend/tests/entrypoint.sh
Labels: DevOps, Bugfix

#296 Fix pipeline
  Jenkinsfile
  docker-compose.yml
Labels: DevOps, Bugfix

#303 make handler for retrive all courses
  backend/courses/app/handlers/course_handlers.py
  backend/courses/app/http/resources/course_resources.py
  backend/courses/app/repositories/course_repository.py
  backend/courses/urls.py
Labels: Backend, Feature

#335 Update urls.py
  backend/server/urls.py
Labels: Backend, Bugfix

#351 Feature/fix tickets
  frontend/src/app/components/my-teacher-lesson/index.jsx
  frontend/src/app/components/my_lesson/index.jsx
  frontend/src/app/core/slices/tickets/getTeacherTicketsSlice.js
  frontend/src/app/core/slices/tickets/getTickets.js
  frontend/src/app/core/slices/tickets/index.js
  frontend/src/app/core/slices/tickets/studentTicketsSlice.js
  frontend/src/app/core/store/index.js
  frontend/src/app/pages/my-lessons/index.jsx
  frontend/src/app/services/tickets/index.js
  frontend/src/app/utils/scheduleServices.js
Labels: Frontend

#354 fix payment sum & add discounts
  frontend/src/app/components/price/index.jsx
  frontend/src/app/pages/abonement/index.jsx
  frontend/src/app/pages/lesson-details/index.jsx
Labels: Frontend, Bugfix

#353 Profile
  frontend/src/app/components/achievement-card/index.jsx
  frontend/src/app/components/achievement/index.jsx
  frontend/src/app/components/achievement/mockData.js
  frontend/src/app/components/header/index.jsx
  frontend/src/app/components/profile/achievementModal.jsx
  frontend/src/app/components/profile/emptyDescription.jsx
  frontend/src/app/components/profile/index.jsx
  frontend/src/app/components/profile/index.scoped.scss
  frontend/src/app/core/slices/profile/getProfileData.js
  frontend/src/app/core/slices/profile/index.js
  frontend/src/app/index.jsx
  frontend/src/app/services/profile/index.js
  frontend/src/assets/public/achievement.svg
  frontend/src/assets/public/defaultBackground.png
  frontend/src/assets/public/emptyDescription.svg
Labels: Frontend

#366 Integrate Jenkins with GitHub Actions
  .github/workflows/main.yml
Labels: DevOps, Feature

#370 Fix workflow environment
  .github/workflows/main.yml
Labels: DevOps, Bugfix

#375 Change path to front and back
  .gitignore
  Jenkinsfile
  Makefile
  docker-compose.yml
  setup.cfg
Labels: DevOps, Bugfix

#376 Fix container names
  Jenkinsfile
Labels: DevOps, Bugfix

#377 Fix path to static
  docker-compose.yml
Labels: DevOps, Bugfix

#380 Fix urls
  .gitmodules
Labels: DevOps, Bugfix

#381 Add sync url
  Jenkinsfile
Labels: DevOps, Bugfix
